// <auto-generated />
using System;
using JwtCookiesScheme;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JwtCookiesScheme.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20241026085124_AddTimeBase")]
    partial class AddTimeBase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("JwtCookiesScheme.Entities.Lockout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LockoutEndTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SsId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("SsId")
                        .IsUnique();

                    b.ToTable("Lockouts");
                });

            modelBuilder.Entity("JwtCookiesScheme.Entities.Permission", b =>
                {
                    b.Property<string>("PermissionId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PermissionName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("PermissionId");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            PermissionId = "Read",
                            PermissionName = "Read"
                        },
                        new
                        {
                            PermissionId = "Write",
                            PermissionName = "Write"
                        },
                        new
                        {
                            PermissionId = "Delete",
                            PermissionName = "Delete"
                        },
                        new
                        {
                            PermissionId = "Execute",
                            PermissionName = "Execute"
                        },
                        new
                        {
                            PermissionId = "FullPermissions",
                            PermissionName = "FullPermissions"
                        });
                });

            modelBuilder.Entity("JwtCookiesScheme.Entities.ResetToken", b =>
                {
                    b.Property<string>("TokenId")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("TokenExpiredAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TokenSerect")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("TokenId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("ResetTokens");
                });

            modelBuilder.Entity("JwtCookiesScheme.Entities.Role", b =>
                {
                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("RoleId");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = "Admin",
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleId = "Owner",
                            RoleName = "Owner"
                        },
                        new
                        {
                            RoleId = "Guest",
                            RoleName = "Guest"
                        },
                        new
                        {
                            RoleId = "User",
                            RoleName = "User"
                        });
                });

            modelBuilder.Entity("JwtCookiesScheme.Entities.RolePermissions", b =>
                {
                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PermissionId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            RoleId = "Admin",
                            PermissionId = "Read"
                        },
                        new
                        {
                            RoleId = "Admin",
                            PermissionId = "Write"
                        },
                        new
                        {
                            RoleId = "Admin",
                            PermissionId = "Delete"
                        },
                        new
                        {
                            RoleId = "Guest",
                            PermissionId = "Read"
                        },
                        new
                        {
                            RoleId = "User",
                            PermissionId = "Read"
                        },
                        new
                        {
                            RoleId = "User",
                            PermissionId = "Write"
                        },
                        new
                        {
                            RoleId = "Owner",
                            PermissionId = "FullPermissions"
                        });
                });

            modelBuilder.Entity("JwtCookiesScheme.Entities.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("UserPassword")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserPhone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserRoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId");

                    b.HasIndex("UserRoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = "2ddbb5e0-3cfc-4a59-a8e4-53657668242e",
                            UserEmail = "Admin@gmail.com",
                            UserName = "Lapphan",
                            UserPassword = "AQAAAAIAAYagAAAAEHlPgvN5vulLJXBhFmlD3WOG+0uiMylIpd6gKYDNSxE4F0NRzKv3YEazElbg7lOa2w==",
                            UserPhone = "",
                            UserRoleId = "Admin"
                        },
                        new
                        {
                            UserId = "377c21f5-3891-4c58-a03d-22cfe839bd45",
                            UserEmail = "Owner@gmail.com",
                            UserName = "Lapphan",
                            UserPassword = "AQAAAAIAAYagAAAAELXmnhmZ4XBaXa9chKmvJEgW6V80ZvPy6ttVWTggW8DR+gDfidP8aUt6kKv5aNyGvQ==",
                            UserPhone = "",
                            UserRoleId = "Owner"
                        });
                });

            modelBuilder.Entity("JwtCookiesScheme.Entities.ResetToken", b =>
                {
                    b.HasOne("JwtCookiesScheme.Entities.User", "User")
                        .WithOne("UserToken")
                        .HasForeignKey("JwtCookiesScheme.Entities.ResetToken", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("JwtCookiesScheme.Entities.RolePermissions", b =>
                {
                    b.HasOne("JwtCookiesScheme.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JwtCookiesScheme.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("JwtCookiesScheme.Entities.User", b =>
                {
                    b.HasOne("JwtCookiesScheme.Entities.Role", "UserRole")
                        .WithMany("Users")
                        .HasForeignKey("UserRoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UserRole");
                });

            modelBuilder.Entity("JwtCookiesScheme.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("JwtCookiesScheme.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("JwtCookiesScheme.Entities.User", b =>
                {
                    b.Navigation("UserToken");
                });
#pragma warning restore 612, 618
        }
    }
}
